### ISSUE TITLE
Send 404 code instead of 500 for non-existant sitemap

### ISSUE THREAD

**Issue by mjangda** [Automattic/msm-sitemap#79]
If a sitemap doesn't exist, we `wp_die` with default params which sends a `500` HTTP code. A `404` would be more appropriate.

**Comment by mdbitz** [comment]
@mjangda > Quick question on this ticket. Currently Metro_Sitemap::build_xml only returns false if year (yyyy), month (mm) or day (dd) is set and not greater than 0.

```
                if ( false === $year && false === $month && false === $day ) {
			$xml = self::build_root_sitemap_xml();
		} else if ( $year > 0 && $month > 0 && $day > 0 ) {
			$xml = self::build_individual_sitemap_xml( $year, $month, $day );
		} else {
			/* Invalid options sent */
			return false;
		}`
```

We can update the wp_die in fullsitemaps template so that it returns the 404 response. However I was wondering if we shouldn't also update `build_individual_sitemap_xml` so that if no Sitemap data exists we return false insteal of the SimpleXMLElement that is generated.  

Is there a  purpose we should be returning the empty xml instead of a 404 if no sitemap xml exists for a date?

**Comment by mjangda** [comment]
> Is there a purpose we should be returning the empty xml instead of a 404 if no sitemap xml exists for a date?

Not that I can think of. Updating `build_individual_sitemap_xml` appropriately seems to make sense here as well.

**Comment by mdbitz** [comment]
Pull Request https://github.com/Automattic/msm-sitemap/pull/105 created to resolve this issue.
